### ISSUE TITLE
欢迎提供想破解的网站

### ISSUE THREAD

**Issue by leng-yue** [leng-yue/Lengyue-Vcode#13]
**仅供学习交流**
**请勿用于非法用途**

仅限JS破解  
每周破解两个幸运的网站

**Comment by zhaipro** [comment]
我很好奇你为什么这么喜欢学习这个内容。

原来关注你这个项目的原因是，我需要冒充多用户注册 Token 账号。

**Comment by wc110302** [comment]
冷月大神，麻烦看一下这个网站呢。
https://makeabooking.flyscoot.com/book/Flight/Select?culture=zh-CN&type=1&dst1=CAN&ast1=SIN&dd=2018-10-15&adt=1&chd=0&inf=0

我现在遇到的这个网站，似乎是使用了distil networks这个反爬虫服务， 如果需要拿到数据就必须带上 cookie，不带 cookie 的请求都会被直接返回 sessionStorage.setItem('distil_referrer', document.referrer);
而这个 cookie 的失效时间又很快，只有 5 分钟左右，并且用的次数多了，大概四五次也会失效，并且我使用 fiddler 跟踪，拿到所有 cookie 参数后，利用这个 cookie 依然无法拿到数据，我猜测其中的原因是因为我多次使用的P参数，虽然每次返回值都不一样，但是都不可用，p参数应该是只能使用一次的。希望这个问题能得到解答

**Comment by leng-yue** [comment]
> 冷月大神，麻烦看一下这个网站呢。
> https://makeabooking.flyscoot.com/book/Flight/Select?culture=zh-CN&type=1&dst1=CAN&ast1=SIN&dd=2018-10-15&adt=1&chd=0&inf=0
> 
> 我现在遇到的这个网站，似乎是使用了distil networks这个反爬虫服务， 如果需要拿到数据就必须带上 cookie，不带 cookie 的请求都会被直接返回 sessionStorage.setItem('distil_referrer', document.referrer);
> 而这个 cookie 的失效时间又很快，只有 5 分钟左右，并且用的次数多了，大概四五次也会失效，并且我使用 fiddler 跟踪，拿到所有 cookie 参数后，利用这个 cookie 依然无法拿到数据，我猜测其中的原因是因为我多次使用的P参数，虽然每次返回值都不一样，但是都不可用，p参数应该是只能使用一次的。希望这个问题能得到解答

我在博客回复你了 Git也提交代码了 你自己看看咯

**Comment by wc110302** [comment]
十分感谢！ 虽然网站错了--！ 手动尴尬 但是都是用的这个反爬虫服务 里面的p参数返回的set-cookie也是一致的 我先消化一下您的代码~ 再次感谢

在 2018-10-10 14:49:27，"lengyue" <notifications@github.com> 写道：


冷月大神，麻烦看一下这个网站呢。
https://makeabooking.flyscoot.com/book/Flight/Select?culture=zh-CN&type=1&dst1=CAN&ast1=SIN&dd=2018-10-15&adt=1&chd=0&inf=0

我现在遇到的这个网站，似乎是使用了distil networks这个反爬虫服务， 如果需要拿到数据就必须带上 cookie，不带 cookie 的请求都会被直接返回 sessionStorage.setItem('distil_referrer', document.referrer);
而这个 cookie 的失效时间又很快，只有 5 分钟左右，并且用的次数多了，大概四五次也会失效，并且我使用 fiddler 跟踪，拿到所有 cookie 参数后，利用这个 cookie 依然无法拿到数据，我猜测其中的原因是因为我多次使用的P参数，虽然每次返回值都不一样，但是都不可用，p参数应该是只能使用一次的。希望这个问题能得到解答

我在博客回复你了 Git也提交代码了 你自己看看咯

**Comment by leng-yue** [comment]
话说没人发网站么 有点闲

**Comment by jiazone** [comment]
冷月大神，有空的话可以看一下 http://index.baidu.com 这个网站呢，想要折线图的数据。但是这个貌似只能通过selenium去拿到呀

**Comment by wc110302** [comment]
> 话说没人发网站么 有点闲

https://m.flight.qunar.com/h5/flight/去哪儿的国际机票查询数据加密- -！用chrome手机调试模式就不用手机登陆了  冷月大大帮忙看看呢

**Comment by zyx521147** [comment]
冷月大神，麻烦看一下https://m.jd.com/   京东的wap端滑块

**Comment by zhaojjhuangjy** [comment]
冷月大神，https://booking.airasia.com/Passengers/Update PC端的，在第3步转到第4步中会跳滑动验证码，麻烦看看

**Comment by leng-yue** [comment]
> 冷月大神，有空的话可以看一下 http://index.baidu.com 这个网站呢，想要折线图的数据。但是这个貌似只能通过selenium去拿到呀

折线图可以直接走AJAX
http://index.baidu.com/Interface/Search/getSubIndex/?res=**[RES]**&type=0&startdate=2018-10-18&enddate=2018-10-24&forecast=0&word=%E5%91%B5%E5%91%B5
其中res参数是打开页面就有的

**Comment by leng-yue** [comment]
> > 话说没人发网站么 有点闲
> 
> [https://m.flight.qunar.com/h5/flight/去哪儿的国际机票查询数据加密-](https://m.flight.qunar.com/h5/flight/%E5%8E%BB%E5%93%AA%E5%84%BF%E7%9A%84%E5%9B%BD%E9%99%85%E6%9C%BA%E7%A5%A8%E6%9F%A5%E8%AF%A2%E6%95%B0%E6%8D%AE%E5%8A%A0%E5%AF%86-) -！用chrome手机调试模式就不用手机登陆了 冷月大大帮忙看看呢

风控太复杂 要做私聊

**Comment by zzqq1** [comment]
真 牛B
麻烦lagou的登陆验证http://lagou.com

**Comment by leng-yue** [comment]
> 真 牛B
> 麻烦lagou的登陆验证http://lagou.com

md5("veenike" + md5(pwd) + "veenike")

**Comment by FishMan132** [comment]
顶象科技的滑块

**Comment by leng-yue** [comment]
> 顶象科技的滑块

这个是流加密啊 懒得开源

**Comment by xiaxichen** [comment]
膜拜大佬

**Comment by Switch-vov** [comment]
微博的验证码，麻烦大佬可以看下吗？需要登录。
https://huati.weibo.cn/super/captcha/?type=pick&page_id=10080817c0fee819b9c79696a382f9634dbd87

是从这个入口进入的，然后弹出这个这个验证码
https://huati.weibo.cn/super/pickoppo?page_id=10080817c0fee819b9c79696a382f9634dbd87

**Comment by zhuyandong** [comment]
搜房fang.com

**Comment by ac-kento** [comment]
豆瓣最近加了腾讯的滑动验证码0.0

**Comment by nqzhang** [comment]
微信的验证码.........

**Comment by Andreby42** [comment]
UC大鱼号的滑动验证码
