### ISSUE TITLE
self._c 及 图像识别

### ISSUE THREAD

**Issue by imdoge** [leng-yue/Lengyue-Vcode#3]
```
        a = self.GetImg(0)
        b = self.GetImg(1)
        c = self.GetImg(2)
```
惊呆。。你是怎么发现图片url的index参数0, 1, 2就是完整图片，有缺块的图片，缺块这3张的呢？
我一开始看html和请求，只发现加载了1和2，也就是有缺块的和缺块本身，想了半天怎么识别出阴影部分。。看别人破极验思路，用的库都是比较图片差异的库，腾讯这个一开始我没发现index=0的完整图片……想半天了
另外看你博客，快速找到请求方法的源码入口那个方法真的很有启发哈~竟然还能这样定位……学习了

**Comment by imdoge** [comment]
self._c这个值怎么来的...

**Comment by leng-yue** [comment]
0的来源 说来话长了 
很久之前 是有完整图片的 但是现在他隐藏了 没有调用了
self._c 再返回内容中 是一个动态的内容

**Comment by imdoge** [comment]
这个我看到了是从内容中动态返回（居然参数都动态返回）
我想问的是你没给出加密算法和加密数据的过程……就给了个结果
最后我没用模拟api和构造数据的方式，我用了模拟拖动的方式

**Comment by imdoge** [comment]
感觉比模拟api方便，一开始我也是两种方案同时走的，模拟api要各种调试代码，看加密…
最后基于一个jq的模拟事件库改了个不规则模拟拖动的方法（虽然成功率中等……说到底两种方案最后还是回到如何模拟人类轨迹的问题）

**Comment by leng-yue** [comment]
哦 这个啊 
你发现我更新代码了没😂
我突然看到一堆star好激动 就把js发出来了 233
今晚有空的话把易盾写一下发出来

**Comment by jerrypy** [comment]
大佬博客怎么删了？ 被天御给和谐了？

**Comment by Flying-a-Fish** [comment]
这种方式请求的成功率高吗，模拟拖动的方式比

**Comment by imdoge** [comment]
还是得看你模拟的策略。。我就是简单加点随机和加速减速，成功很一般
不知博主怎么模拟，我看还有大佬用什么回归和机器学习的。。

**Comment by leng-yue** [comment]
其实我自己用的机器学习 不太想发出来😂

**Comment by leng-yue** [comment]
我删博客 是因为我服务器忘了备份 之前不小心删了。。 重建博客文章暂时没时间迁移

**Comment by imdoge** [comment]
有9成成功吗 (⊙o⊙)

**Comment by Flying-a-Fish** [comment]
用你的代码启动的时候deced = JS.call("decrypt", enced, Encrypt_Key)这行代码报了一个
execjs._exceptions.ProgramError: TypeError: 'undefined' 为空或不是对象
127.0.0.1 - - [06/Mar/2018 15:47:24] "POST /parse?x=474 HTTP/1.1" 500 -
这样的错，是什么原因导致的呢

**Comment by zhaipro** [comment]
我也遇到了与Flying-a-Fish相同的问题，期待该项目的持续更新。
