### ISSUE TITLE
阿里云的滑动验证码+点击字体验证

### ISSUE THREAD

**Issue by yunhai0920** [leng-yue/Lengyue-Vcode#30]
请问删除的阿里云验证码破解可以发一份吗？

**Comment by zhaojjhuangjy** [comment]
同求一份，谢谢，568759444@qq.com

**Comment by leng-yue** [comment]
删除的早就失效了 _n 算法没给
需要API的可以发邮件

**Comment by ivuex** [comment]
尊敬的 @leng-yue 大神 及 各位大佬：
我也想想要 阿里云的滑动破解资料，源码，轨迹数据，思路 都稀饭。
我的代码滑动完成了在web页面登录框下边总是报错：
```
"""哎呀，出错了，点击刷新再来一次，(error:GRAEmv)"""
```
#error码每次都会变，估计是hash生成的
我的代码如下，求指点：
```
# -*- coding:utf-8 -*-

from selenium import webdriver
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from time import sleep
from selenium.common.exceptions import TimeoutException
from selenium.webdriver import ActionChains
import random
from secret import secret # 这是用户名和密码字典

# driver = webdriver.PhantomJS()
browser = webdriver.Chrome()

def get_random(min, max):
    return  random.choice(list(range(min, max)))

def get_track(distance):
    """
    根据便宜量获取移动轨迹
    :param distance:
    :return: 移动轨迹
    """

    # 移动轨迹
    track = []
    # 当前位移
    current = 0
    # 减速阈值
    # mid = distance * 4 / 5
    # mid = distance * 3 / 5
    mid = distance * 7 / 10
    # 计算间隔
    # t = 0.2
    t = 0.1
    # 初速度
    v = 4

    while current < distance:
        if current < mid:
            # 加速度为正2
            a = 4 + get_random(-2,2)
        else:
            # 加速度为负3
            a = -6 + get_random(-2,2)
        # 初速度v0
        v0 = v
        # 当前速度 v = v0 + at
        v = v0 + a * t
        # 移动距离x = v0t + 1/2 * a * t^2
        move = v0 * t + 1 / 2 * a * t * t
        # 当前位移
        current += move
        # 加入轨迹
        track.append(round(move))
    return track


def move_to_end(slider, track):
    """
    按轨迹拖动滑块
    :param slider:
    :param track:
    :return:
    """
    ActionChains(browser).click_and_hold(slider).perform()
    for x in track:
        ActionChains(browser).move_by_offset(xoffset=x, yoffset=0).perform()
    sleep(0.5)
    ActionChains(browser).release().perform()


def get_distance(railway, slider):
    length = railway.size['width'] - slider.size['width'] + 20 # 这里我不加点数字好像滑不完，求指点
    return length


timeout = 20
wait = WebDriverWait(browser, timeout)

browser.get('https://login.taobao.com/member/login.jhtml')

sleep(3)
pwdlogins = browser.find_elements_by_class_name("J_Quick2Static")
sleep(3)
for pwdlogin in pwdlogins:
    pwdlogin.click()
# try:
#     if pwdlogin:
#         pwdlogin.click()
# except TimeoutException:
#     print('没有.J_Quick2Static元素')
#     # sleep(0.2)

username = wait.until(
    EC.presence_of_element_located((By.ID, 'TPL_username_1'))
)
sleep(0.5)
username.clear()
sleep(0.5)
username.send_keys(secret['uname'])
password = wait.until(
    EC.presence_of_element_located((By.ID, 'TPL_password_1'))
)
sleep(0.5)
password.clear()
sleep(0.5)
password.send_keys(secret['pwd'])

# 如果需要滑块认证就做滑动操作
sleep(2)
# pwdlogins = browser.find_elements_by_class_name("J_Quick2Static")
slider = browser.find_element_by_css_selector('.nc_iconfont.btn_slide')
railway = browser.find_element_by_css_selector('.slidetounlock .nc-lang-cnt')
if slider and railway:
    distance = get_distance(railway, slider)
    move_to_end(slider, get_track(distance)) # 报错: """哎呀，出错了，点击刷新再来一次，(error:GRAEmv)""" #error码每次都会变，估计是hash生成的
    sleep(2)

submit = wait.until(EC.presence_of_element_located((By.ID, 'J_SubmitStatic')))
sleep(0.5)
submit.click()

# driver.get_cookies()取得cookie
cookie = "; ".join([item["name"] + "=" + item["value"] + "\n" for item in browser.get_cookies()])
print(cookie)
# 然后带上cookie登录后的页面去请求页面
```

谢谢了

**Comment by leng-yue** [comment]
> 尊敬的 @leng-yue 大神 及 各位大佬：
> 我也想想要 阿里云的滑动破解资料，源码，轨迹数据，思路 都稀饭。
> 我的代码滑动完成了在web页面登录框下边总是报错：
> 
> ```
> """哎呀，出错了，点击刷新再来一次，(error:GRAEmv)"""
> ```
> #error码每次都会变，估计是hash生成的
> 我的代码如下，求指点：
> 
> ```
> # -*- coding:utf-8 -*-
> 
> from selenium import webdriver
> from selenium.webdriver.support.ui import WebDriverWait
> from selenium.webdriver.support import expected_conditions as EC
> from selenium.webdriver.common.by import By
> from time import sleep
> from selenium.common.exceptions import TimeoutException
> from selenium.webdriver import ActionChains
> import random
> from secret import secret # 这是用户名和密码字典
> 
> # driver = webdriver.PhantomJS()
> browser = webdriver.Chrome()
> 
> def get_random(min, max):
>     return  random.choice(list(range(min, max)))
> 
> def get_track(distance):
>     """
>     根据便宜量获取移动轨迹
>     :param distance:
>     :return: 移动轨迹
>     """
> 
>     # 移动轨迹
>     track = []
>     # 当前位移
>     current = 0
>     # 减速阈值
>     # mid = distance * 4 / 5
>     # mid = distance * 3 / 5
>     mid = distance * 7 / 10
>     # 计算间隔
>     # t = 0.2
>     t = 0.1
>     # 初速度
>     v = 4
> 
>     while current < distance:
>         if current < mid:
>             # 加速度为正2
>             a = 4 + get_random(-2,2)
>         else:
>             # 加速度为负3
>             a = -6 + get_random(-2,2)
>         # 初速度v0
>         v0 = v
>         # 当前速度 v = v0 + at
>         v = v0 + a * t
>         # 移动距离x = v0t + 1/2 * a * t^2
>         move = v0 * t + 1 / 2 * a * t * t
>         # 当前位移
>         current += move
>         # 加入轨迹
>         track.append(round(move))
>     return track
> 
> 
> def move_to_end(slider, track):
>     """
>     按轨迹拖动滑块
>     :param slider:
>     :param track:
>     :return:
>     """
>     ActionChains(browser).click_and_hold(slider).perform()
>     for x in track:
>         ActionChains(browser).move_by_offset(xoffset=x, yoffset=0).perform()
>     sleep(0.5)
>     ActionChains(browser).release().perform()
> 
> 
> def get_distance(railway, slider):
>     length = railway.size['width'] - slider.size['width'] + 20 # 这里我不加点数字好像滑不完，求指点
>     return length
> 
> 
> timeout = 20
> wait = WebDriverWait(browser, timeout)
> 
> browser.get('https://login.taobao.com/member/login.jhtml')
> 
> sleep(3)
> pwdlogins = browser.find_elements_by_class_name("J_Quick2Static")
> sleep(3)
> for pwdlogin in pwdlogins:
>     pwdlogin.click()
> # try:
> #     if pwdlogin:
> #         pwdlogin.click()
> # except TimeoutException:
> #     print('没有.J_Quick2Static元素')
> #     # sleep(0.2)
> 
> username = wait.until(
>     EC.presence_of_element_located((By.ID, 'TPL_username_1'))
> )
> sleep(0.5)
> username.clear()
> sleep(0.5)
> username.send_keys(secret['uname'])
> password = wait.until(
>     EC.presence_of_element_located((By.ID, 'TPL_password_1'))
> )
> sleep(0.5)
> password.clear()
> sleep(0.5)
> password.send_keys(secret['pwd'])
> 
> # 如果需要滑块认证就做滑动操作
> sleep(2)
> # pwdlogins = browser.find_elements_by_class_name("J_Quick2Static")
> slider = browser.find_element_by_css_selector('.nc_iconfont.btn_slide')
> railway = browser.find_element_by_css_selector('.slidetounlock .nc-lang-cnt')
> if slider and railway:
>     distance = get_distance(railway, slider)
>     move_to_end(slider, get_track(distance)) # 报错: """哎呀，出错了，点击刷新再来一次，(error:GRAEmv)""" #error码每次都会变，估计是hash生成的
>     sleep(2)
> 
> submit = wait.until(EC.presence_of_element_located((By.ID, 'J_SubmitStatic')))
> sleep(0.5)
> submit.click()
> 
> # driver.get_cookies()取得cookie
> cookie = "; ".join([item["name"] + "=" + item["value"] + "\n" for item in browser.get_cookies()])
> print(cookie)
> # 然后带上cookie登录后的页面去请求页面
> ```
> 谢谢了

事实上你用SELENIUM就会挂

**Comment by leohuangyy** [comment]
> > 尊敬的 @leng-yue 大神 及 各位大佬：
> > 我也想想要 阿里云的滑动破解资料，源码，轨迹数据，思路 都稀饭。
> > 我的代码滑动完成了在web页面登录框下边总是报错：
> > ```
> > """哎呀，出错了，点击刷新再来一次，(error:GRAEmv)"""
> > ```
> > #error码每次都会变，估计是hash生成的
> > 我的代码如下，求指点：
> > ```
> > # -*- coding:utf-8 -*-
> > 
> > from selenium import webdriver
> > from selenium.webdriver.support.ui import WebDriverWait
> > from selenium.webdriver.support import expected_conditions as EC
> > from selenium.webdriver.common.by import By
> > from time import sleep
> > from selenium.common.exceptions import TimeoutException
> > from selenium.webdriver import ActionChains
> > import random
> > from secret import secret # 这是用户名和密码字典
> > 
> > # driver = webdriver.PhantomJS()
> > browser = webdriver.Chrome()
> > 
> > def get_random(min, max):
> >     return  random.choice(list(range(min, max)))
> > 
> > def get_track(distance):
> >     """
> >     根据便宜量获取移动轨迹
> >     :param distance:
> >     :return: 移动轨迹
> >     """
> > 
> >     # 移动轨迹
> >     track = []
> >     # 当前位移
> >     current = 0
> >     # 减速阈值
> >     # mid = distance * 4 / 5
> >     # mid = distance * 3 / 5
> >     mid = distance * 7 / 10
> >     # 计算间隔
> >     # t = 0.2
> >     t = 0.1
> >     # 初速度
> >     v = 4
> > 
> >     while current < distance:
> >         if current < mid:
> >             # 加速度为正2
> >             a = 4 + get_random(-2,2)
> >         else:
> >             # 加速度为负3
> >             a = -6 + get_random(-2,2)
> >         # 初速度v0
> >         v0 = v
> >         # 当前速度 v = v0 + at
> >         v = v0 + a * t
> >         # 移动距离x = v0t + 1/2 * a * t^2
> >         move = v0 * t + 1 / 2 * a * t * t
> >         # 当前位移
> >         current += move
> >         # 加入轨迹
> >         track.append(round(move))
> >     return track
> > 
> > 
> > def move_to_end(slider, track):
> >     """
> >     按轨迹拖动滑块
> >     :param slider:
> >     :param track:
> >     :return:
> >     """
> >     ActionChains(browser).click_and_hold(slider).perform()
> >     for x in track:
> >         ActionChains(browser).move_by_offset(xoffset=x, yoffset=0).perform()
> >     sleep(0.5)
> >     ActionChains(browser).release().perform()
> > 
> > 
> > def get_distance(railway, slider):
> >     length = railway.size['width'] - slider.size['width'] + 20 # 这里我不加点数字好像滑不完，求指点
> >     return length
> > 
> > 
> > timeout = 20
> > wait = WebDriverWait(browser, timeout)
> > 
> > browser.get('https://login.taobao.com/member/login.jhtml')
> > 
> > sleep(3)
> > pwdlogins = browser.find_elements_by_class_name("J_Quick2Static")
> > sleep(3)
> > for pwdlogin in pwdlogins:
> >     pwdlogin.click()
> > # try:
> > #     if pwdlogin:
> > #         pwdlogin.click()
> > # except TimeoutException:
> > #     print('没有.J_Quick2Static元素')
> > #     # sleep(0.2)
> > 
> > username = wait.until(
> >     EC.presence_of_element_located((By.ID, 'TPL_username_1'))
> > )
> > sleep(0.5)
> > username.clear()
> > sleep(0.5)
> > username.send_keys(secret['uname'])
> > password = wait.until(
> >     EC.presence_of_element_located((By.ID, 'TPL_password_1'))
> > )
> > sleep(0.5)
> > password.clear()
> > sleep(0.5)
> > password.send_keys(secret['pwd'])
> > 
> > # 如果需要滑块认证就做滑动操作
> > sleep(2)
> > # pwdlogins = browser.find_elements_by_class_name("J_Quick2Static")
> > slider = browser.find_element_by_css_selector('.nc_iconfont.btn_slide')
> > railway = browser.find_element_by_css_selector('.slidetounlock .nc-lang-cnt')
> > if slider and railway:
> >     distance = get_distance(railway, slider)
> >     move_to_end(slider, get_track(distance)) # 报错: """哎呀，出错了，点击刷新再来一次，(error:GRAEmv)""" #error码每次都会变，估计是hash生成的
> >     sleep(2)
> > 
> > submit = wait.until(EC.presence_of_element_located((By.ID, 'J_SubmitStatic')))
> > sleep(0.5)
> > submit.click()
> > 
> > # driver.get_cookies()取得cookie
> > cookie = "; ".join([item["name"] + "=" + item["value"] + "\n" for item in browser.get_cookies()])
> > print(cookie)
> > # 然后带上cookie登录后的页面去请求页面
> > ```
> > 谢谢了
> 
> 事实上你用SELENIUM就会挂

用selenium就一定没办法规避滑动框滑动后出现的"哎呀，出错了，点击刷新再来一次”的这个问题吗？

**Comment by Andreby42** [comment]
我也是用selenium 就会出现 "哎呀，出错了，点击刷新再来一次”这个问题，有人说用chroedriver 低版本的可以解决。但是我试了不好用

**Comment by trevan1994** [comment]
哎呀，出错了  这个可以解决的,需要 修改chromedriver ,然后就是轨迹 ,其实感觉这个很坑,因为通过chromedriver 模拟滑动会 出错 ,但是win32api 滑动就没问题!

**Comment by Andreby42** [comment]
> 这个问题可以解决的 需要修改 chromedriver 中的一个特征，然后需要修改 navigator.webdriver 修改后 navigator.webdriver 会变更，但是感觉这种方法也会有写缺陷 'webdriver' in navigator 还是会为 true, 还是 delete navigator.webdriver 吧 其他模拟拖动轨迹好像没有什么特别的要求！
也就是说删除掉 navigator.webdriver的属性？

**Comment by xLabel** [comment]
插眼，以后TP

**Comment by zi-ming** [comment]
请问阿里云滑动验证码破解可以发我一份吗，1564603397@qq.com

**Comment by Galaxyobe** [comment]
请问阿里云滑动验证码破解可以发我一份吗，谢谢！417270467@qq.com

**Comment by baby5** [comment]
https://github.com/miyakogi/pyppeteer +
https://segmentfault.com/a/1190000019539509
试试

**Comment by adamchenJ** [comment]
请问阿里云滑动验证码破解可以发我一份吗，949633929@qq.com
