### ISSUE TITLE
深度学习得那个是怎么使用得，能给个demo吗

### ISSUE THREAD

**Issue by mengpengfei** [leng-yue/Lengyue-Vcode#37]

**Comment by leng-yue** [comment]
可以直接丢到caffe 改个datalayer就得了

**Comment by mengpengfei** [comment]
请问下，我用深度学习训练了一些英数验证码，然后得到一个模型，过了一段时间之后，我又有了新得风格的样本，可以在原来的模型上继续训练吗，如果在原来的模型使用新的样本继续训练的话， 最后得到的模型，还能识别以前的那些风格的验证码

**Comment by mengpengfei** [comment]
需要那么多，你说的千万起跑，是千万张图片，几千种类型才可以吗

**Comment by mengpengfei** [comment]
需要那么多，你说的千万起跑，是千万张图片，几千种类型才可以吗

**Comment by mengpengfei** [comment]
那感觉深度学习处理验证码没什么意义了，各个击破的话用传统的方法预处理，然后识别就可以了

**Comment by mengpengfei** [comment]
那感觉深度学习处理验证码没什么意义了，各个击破的话用传统的方法预处理，然后识别就可以了

**Comment by mengpengfei** [comment]
如果想做个通用模型的话，不同风格得验证码都需要训练吗

**Comment by mengpengfei** [comment]
如果我做图片预处理，先将训练集二值化得话，用cnn与不做预处理有什么差别呢

**Comment by mengpengfei** [comment]
bstm+ssd得是怎么读到训练数据的，那个得用法能不能说下
