### ISSUE TITLE
cnn验证码识别

### ISSUE THREAD

**Issue by ETCartman** [leng-yue/Lengyue-Vcode#7]
您好,  刚试了下CNN破解阿里的验证码,效果不是很好,请问您用的`gen_captcha_text_and_image`是这个吗
```python
def gen_captcha_text_and_image():
	image = ImageCaptcha()

	captcha_text = random_captcha_text()
	captcha_text = ''.join(captcha_text)

	captcha = image.generate(captcha_text)

	captcha_image = Image.open(captcha)
	captcha_image = np.array(captcha_image)
	return captcha_text, captcha_image
```

**Comment by kjfcpua** [comment]
你好我现在也在尝试破解ali的滑动验证码，这个cnn程序好像有问题,无法识别4位的数字字母组合验证码，我是用网上打码平台识别的这个验证码，但是在最后一步请求http://cf.aliyun.com/captcha/checkcode.jsonp地址时，无法得到server返回的sig值，我理解_n,这个参数，就是曾经成功过的验证的值，我现在用验证成功的
n: 109#ZJla7KuMa...值，也无法得到sig，现在卡在最后一步，你要是有好的思路，麻烦分享下.我qq，2404786121
