### ISSUE TITLE
代码请求http://cf.aliyun.com/captcha/checkcode.jsonp,已经无法拿到server返回的sig值,报错

### ISSUE THREAD

**Issue by kjfcpua** [leng-yue/Lengyue-Vcode#8]
你好我现在也在尝试破解ali的滑动验证码，这个cnn程序好像有问题,无法识别4位的数字字母组合验证码，我是用网上打码平台识别的这个验证码，但是在最后一步请求http://cf.aliyun.com/captcha/checkcode.jsonp地址时，无法得到server返回的sig值，我理解_n,这个参数，就是曾经成功过的验证的值，我现在用验证成功的
n: 109#ZJla7KuMa...值，也无法得到sig，现在卡在最后一步，你要是有好的思路，麻烦分享下.我qq，2404786121，价格好商量

**Comment by leng-yue** [comment]
目前阿里已经更新 原有的固定key不可用 我这边可以提供付费服务
